# Generated by Django 3.0.3 on 2020-05-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_currency_pnlper'),
    ]

    operations = [
        migrations.CreateModel(
            name='index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField(blank=True, default=None, null=True)),
                ('pnl', models.FloatField(blank=True, default=None, null=True)),
                ('pnlper', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='currency',
            name='pnlper',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
