# Generated by Django 3.0.3 on 2020-05-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200512_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='indexes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.CharField(max_length=200, null=True)),
                ('pnl', models.FloatField(blank=True, default=None, null=True)),
                ('pnlper', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='index',
        ),
    ]
