# Generated by Django 3.0.3 on 2020-05-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200512_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='stocknews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=400, null=True)),
                ('content', models.CharField(max_length=400, null=True)),
                ('imgurl', models.CharField(max_length=400, null=True)),
            ],
        ),
    ]
