# Generated by Django 3.0.3 on 2020-05-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20200515_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='pnlper',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
