# Generated by Django 3.0.3 on 2020-05-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20200515_0829'),
    ]

    operations = [
        migrations.CreateModel(
            name='equities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.CharField(max_length=200, null=True)),
                ('pnl', models.FloatField(blank=True, default=None, null=True)),
                ('pnlper', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
    ]
